/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import EDD.BinaryTree;
import EDD.TreeNode;
import GUI.Buscar;
import java.awt.Color;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

public class InterfazInicio extends javax.swing.JFrame {

    private BinaryTree binaryTree;
    private boolean jsonLoaded = false;
    /**
     * Creates new form InterfazInicio
     */
    public InterfazInicio() {
        setUndecorated(true);
        initComponents();
        binaryTree = new BinaryTree();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CargarNuevaClave = new javax.swing.JButton();
        MostrarArbol = new javax.swing.JButton();
        Determinar = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));

        Salir.setBackground(new java.awt.Color(204, 204, 204));
        Salir.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Salir.setText("X");
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalirMouseExited(evt);
            }
        });
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setText("Clave Dicotómica");

        CargarNuevaClave.setBackground(new java.awt.Color(255, 255, 102));
        CargarNuevaClave.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        CargarNuevaClave.setText("Cargar una nueva clave");
        CargarNuevaClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarNuevaClaveActionPerformed(evt);
            }
        });

        MostrarArbol.setBackground(new java.awt.Color(255, 255, 102));
        MostrarArbol.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        MostrarArbol.setText("Mostrar como árbol");
        MostrarArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarArbolActionPerformed(evt);
            }
        });

        Determinar.setBackground(new java.awt.Color(255, 255, 102));
        Determinar.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Determinar.setText("Determinar especie");
        Determinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeterminarActionPerformed(evt);
            }
        });

        Buscar.setBackground(new java.awt.Color(255, 255, 102));
        Buscar.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Buscar.setText("Buscar especie");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 64, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(178, 178, 178)
                            .addComponent(Buscar)
                            .addGap(15, 15, 15))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(138, 138, 138)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(MostrarArbol)
                                .addComponent(Determinar))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(CargarNuevaClave)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Salir)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(CargarNuevaClave)
                .addGap(36, 36, 36)
                .addComponent(MostrarArbol)
                .addGap(34, 34, 34)
                .addComponent(Determinar)
                .addGap(36, 36, 36)
                .addComponent(Buscar)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirMouseClicked

    private void SalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseEntered
        Salir.setForeground(Color.red);
    }//GEN-LAST:event_SalirMouseEntered

    private void SalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseExited
        Salir.setForeground(Color.black);
    }//GEN-LAST:event_SalirMouseExited

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void MostrarArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarArbolActionPerformed
        if (jsonLoaded) {
            binaryTree.visualizeTree();
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, cargue un archivo JSON primero.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_MostrarArbolActionPerformed

    private void CargarNuevaClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarNuevaClaveActionPerformed

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Seleccione la clave en formato JSON");
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Archivos JSON", "json"));

        int seleccion = fileChooser.showOpenDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            String rutaArchivo = archivo.getAbsolutePath();

            try {
                
                JSONParser parser = new JSONParser();
                JSONObject jsonObject = (JSONObject) parser.parse(new FileReader(rutaArchivo));

                binaryTree.buildTreeFromJson(rutaArchivo);
                jsonLoaded = true;

                JOptionPane.showMessageDialog(this, "Archivo cargado correctamente: " + archivo.getName());
            } catch (IOException | ParseException e) {
                JOptionPane.showMessageDialog(this, "Error al cargar el archivo: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                jsonLoaded = false;
            }
        }
    }//GEN-LAST:event_CargarNuevaClaveActionPerformed

    private void DeterminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeterminarActionPerformed
   if (binaryTree.getRoot() == null) {
        JOptionPane.showMessageDialog(this, "Debe cargar una clave antes de determinar una especie.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    TreeNode currentNode = binaryTree.getRoot();

    while (currentNode != null) {
        
        if (currentNode.getHijoSi() == null && currentNode.getHijoNo() == null) {
            JOptionPane.showMessageDialog(this, "La especie encontrada es: " + currentNode.getQuestion(), "Resultado", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

      
        int respuesta = JOptionPane.showConfirmDialog(this, currentNode.getQuestion(), "Pregunta", JOptionPane.YES_NO_OPTION);

       
        if (respuesta == JOptionPane.YES_OPTION) {
            currentNode = currentNode.getHijoSi();
        } else {
            currentNode = currentNode.getHijoNo();
        }
    }

 
    JOptionPane.showMessageDialog(this, "No se encontró una especie en el árbol.", "Error", JOptionPane.ERROR_MESSAGE);


    }//GEN-LAST:event_DeterminarActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        Buscar busqueda = new Buscar(this.binaryTree);
        busqueda.setLocationRelativeTo(null);
        busqueda.setVisible(true);
        
    }//GEN-LAST:event_BuscarActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton CargarNuevaClave;
    private javax.swing.JButton Determinar;
    private javax.swing.JButton MostrarArbol;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
